name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - dev
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Build the Docker image
      run: docker build -t sacoefrancis/balckswan:${{ github.sha }} .
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image to Docker Hub
      run: docker push sacoefrancis/balckswan:${{ github.sha }}

